### ISSUE TITLE
Please create a non-prelease version.

### ISSUE THREAD

**Issue by mthamil** [joelweiss/Log4net.Appender.Serilog#1]
This library has been quite useful for integrating with some legacy code, but due to policies on my team I can't use pre-release packages. I could fork it, but I just wanted to let you know.

**Comment by xantari** [comment]
I second this!

**Comment by mikeblakeuk** [comment]
@joelweiss is there a release version of this?

**Comment by joelweiss** [comment]
Sorry for not getting back to you earlier, I must have missed the notifications.

I updated the project to target netstandard 2.0

I got done removing log4net from my projects a few weeks ago, so I can't test this in production, I released a new version on [nuget](https://www.nuget.org/packages/Log4net.Appender.Serilog/1.0.7-Beta), if you can test it I would appreciate it, if there are no issues I will release a *Release* version.

**Comment by maza-soptim** [comment]
I just found your project while searching for a log4net/Serilog integration.

The version 1.0.7-Beta works for me and I would highly appreciate, if you could make a regular release.

**Comment by joelweiss** [comment]
Finally released a non beta version [1.0.9](https://www.nuget.org/packages/Log4net.Appender.Serilog/1.0.9),
