### ISSUE TITLE
log4net 2.0.15 compatibility

### ISSUE THREAD

**Issue by koleksiikovalchuk** [joelweiss/Log4net.Appender.Serilog#6]
Hi. After updating log4net to 2.0.15 I faced the following issue:
```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Log4net.Appender.Serilog.SerilogAppender' threw an exception.
  Source=Log4net.Appender.Serilog
  StackTrace:
   at Log4net.Appender.Serilog.Configuration.Configure(ILogger logger)

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentException: Instance field 'm_format' is not defined for type 'log4net.Util.SystemStringFormat'
```
I see that you've fixed it 2 days ago, but nuget.org
https://www.nuget.org/packages/Log4net.Appender.Serilog
is still having the most recent version of 1.0.11, published at 8/14/2019.
Don't wanna copy-paste the code to make things work in my project.
Could you please tell me, when do you plan to roll-out a new version of Log4net.Appender.Serilog NuGet package?
Thank you

**Comment by joelweiss** [comment]
nuget released.
